[package]
name = "matcher-ws-wip"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.17"
url = "2.3"
futures-util = "0.3"
serde_json = "1.0.120"
